# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iy0tsH94xFEWdK8UY6p51ix65YAa6_tS
"""

import numpy as np
import joblib
import streamlit as st

# ---------------- Page Config ----------------
st.set_page_config(
    page_title="CGPA → Package Predictor",
    page_icon="📈",
    layout="centered"
)

# ---------------- Load Model ----------------
@st.cache_resource
def load_model():
    model = joblib.load("cgpa_package_model.pkl")
    return model

model = load_model()

# ---------------- UI ----------------
st.title("CGPA → Package Predictor 📊")
st.write(
    "This app gives a rough estimate of your package (in LPA) based on your CGPA. "
    "Use it as **motivation**, not as a limit."
)

st.markdown("---")

with st.form("prediction_form"):
    name = st.text_input("Your Name")

    cgpa = st.number_input(
        "Your CGPA",
        min_value=4.0,
        max_value=10.0,
        step=0.01,
        format="%.2f",
        help="Enter a CGPA between 4.00 and 10.00"
    )

    submitted = st.form_submit_button("Predict Package 💼")

if submitted:
    if not name.strip():
        st.warning("Naam daal pehle, phir prediction chalega 🙂")
    else:
        # Model expects a 2D array: [[cgpa]]
        X_input = np.array([[cgpa]])
        y_pred = model.predict(X_input)

        # Because you trained with y as a DataFrame, shape is (1, 1)
        try:
            package_lpa = float(y_pred[0][0])
        except Exception:
            package_lpa = float(y_pred[0])

        st.markdown("### 🎯 Prediction Result")
        st.success(f"Estimated Package: **{package_lpa:.2f} LPA**")

        st.markdown(
            f"""
            **Hello {name},**
            this is just a simple prediction — you can absolutely earn **more** than this.

            Stay hungry, stay sharp — your hustle isn't over yet. 🔥
            """
        )

st.markdown("---")
st.caption("Made for learning & motivation. Your future > any model.")
